  import type { Metadata } from "next";
  import { Caveat, Geist, Geist_Mono, Sawarabi_Mincho } from "next/font/google";
  import "./globals.css";
  import { MenuContextProvider } from "./(context)/MenuBtnContext";
  import Navbar from "./(components)/Navbar/Navbar";
  import Footer from "./(components)/Footer/Footer";
  import { Toaster } from "react-hot-toast";

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  const caveat = Caveat({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-caveat",
  });

  const sawarabiMincho = Sawarabi_Mincho({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-sawarabi-mincho",
  });

  export const metadata: Metadata = {
    title: "My Portfolio",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${caveat.variable} ${sawarabiMincho.variable} antialiased`}
        >
          <MenuContextProvider>
            <Navbar/>
            <Toaster position="top-right" />
            {children}
            <Footer/>
          </MenuContextProvider>
        </body>
      </html>
    );
  }
